// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYQFnhupq9GiL7P0D5VeIftWvh3ePTKSs',
    appId: '1:471683042983:web:c96bd7eda706898337d582',
    messagingSenderId: '471683042983',
    projectId: 'smart-toolbox-b0455',
    authDomain: 'smart-toolbox-b0455.firebaseapp.com',
    storageBucket: 'smart-toolbox-b0455.firebasestorage.app',
    measurementId: 'G-SFYV8RW1NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7RvBllF-aHS8zPZ_9-zYt7PJMfVBeitU',
    appId: '1:471683042983:android:8a038e1da9f462a837d582',
    messagingSenderId: '471683042983',
    projectId: 'smart-toolbox-b0455',
    storageBucket: 'smart-toolbox-b0455.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArgQ1f1_NlI4u1jVBqiSIV7U9p7KXHNeg',
    appId: '1:471683042983:ios:cdb9af247220434c37d582',
    messagingSenderId: '471683042983',
    projectId: 'smart-toolbox-b0455',
    storageBucket: 'smart-toolbox-b0455.firebasestorage.app',
    iosBundleId: 'com.layer6.tooltrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArgQ1f1_NlI4u1jVBqiSIV7U9p7KXHNeg',
    appId: '1:471683042983:ios:cdb9af247220434c37d582',
    messagingSenderId: '471683042983',
    projectId: 'smart-toolbox-b0455',
    storageBucket: 'smart-toolbox-b0455.firebasestorage.app',
    iosBundleId: 'com.layer6.tooltrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYQFnhupq9GiL7P0D5VeIftWvh3ePTKSs',
    appId: '1:471683042983:web:0e55df5e3184d7f537d582',
    messagingSenderId: '471683042983',
    projectId: 'smart-toolbox-b0455',
    authDomain: 'smart-toolbox-b0455.firebaseapp.com',
    storageBucket: 'smart-toolbox-b0455.firebasestorage.app',
    measurementId: 'G-BMMTB1BVP3',
  );
}
